title: "[Paper/Resource]: "
body:
  - type: markdown
    attributes:
      value: |
        ## 📚 Research & Technical Reference
        *Use this form to suggest literature or resources that impact the research conducted with this library or its core development.*

  - type: input
    id: full_title
    attributes:
      label: Full Resource Title
      description: "The original name of the paper, blog post, or documentation."
      placeholder: "e.g., Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks"
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link or DOI
      placeholder: "https://doi.org/10.1038/..."
    validations:
      required: true

  - type: checkboxes
    id: resource_category
    attributes:
      label: Resource Category
      description: "Select the themes that define this resource."
      options:
        - label: Similar AI Projects
        - label: Relevant LLM Architectures
        - label: Molecular Representation Learning
    validations:
      required: true

  - type: textarea
    id: relevance
    attributes:
      label: Why is this relevant to our project?
      description: "Briefly explain how this helps us solve a current problem or improve a specific module."
      placeholder: "This paper describes a better way to handle XYZ..."
    validations:
      required: true

  - type: dropdown
    id: reading_priority
    attributes:
      label: Reading Priority
      options:
        - "🔴 Critical: Read ASAP for current sprint"
        - "🟡 Important: Relevant for upcoming features"
        - "🔵 Informational: Background knowledge / State of the art"
    validations:
      required: true
